---
- name: Verify memory and cache sizes
  assert:
    that:
      - geth_cont_mem_limit|int > geth_cache_size|int
    fail_msg: 'Memory limit cant be lower than cache: {{ geth_cont_mem_limit }} > {{ geth_cache_size }}'
    success_msg: 'Memory limit is higher than cache size: {{ geth_cont_mem_limit }} > {{ geth_cache_size }}'
    quiet: true
