---
- name: Geth | Enable ports on firewall
  iptables:
    comment: '{{ geth_cont_name }} {{ item }}'
    jump: ACCEPT
    action: insert
    chain: DOCKER-USER
    source: '0.0.0.0/0'
    protocol: '{{ item }}'
    destination_port: '{{ geth_port | string }}'
  with_items:
    - tcp
    - udp
  notify:
    - Save iptables rules
