---
- import_tasks: checks.yml
- import_tasks: generate.yml
- import_tasks: trusted_peers.yml
- import_tasks: init.yml
  when: geth_init_enabled
- import_tasks: container.yml
- import_tasks: wrappers.yml
- import_tasks: save_enode.yml
- import_tasks: consul.yml
  when: geth_consul_enabled
