---
- name: Create Geth console attach wrapper
  template:
    src: 'attach.sh.j2'
    dest: '{{ geth_cont_vol }}/attach.sh'
    owner: 'root'
    group: 'docker'
    mode: 0750

- name: Create Geth JSON RPC wrapper script
  template:
    src: 'rpc.sh.j2'
    dest: '{{ geth_cont_vol }}/rpc.sh'
    owner: 'root'
    group: 'docker'
    mode: 0750
